name: "Check python package"
description: "Check a python package and commit changes for quality"
inputs:
  version_path:
    required: false
    description: The path to file that contains the version string.
  version_variable:
    required: false
    description: The name of the version variable.
    default: __version__
runs:
  
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.repository.default_branch }}
    - uses: actions/checkout@v3
    - name: "Check version"
      run: |
        [ ${{ github.event.repository.default_branch }} == ${{ github.ref_name }} ] || $(
        git fetch
        git checkout ${{ github.event.repository.default_branch }}
        git checkout ${{ github.ref_name }}
        python ${{ github.action_path }}/scripts/check_version.py ${{ inputs.version_path }} ${{ inputs.version_variable }} ${{ github.event.repository.default_branch }} || $(python ${{ github.action_path }}/scripts/next_version.py ${{ inputs.version_path }} ${{ inputs.version_variable }} ${{ github.event.repository.default_branch }} && git config user.name github-actions &&
          git config user.email github-actions@github.com &&
          git add . &&
          git commit -m "Update micro version" &&
          git push --set-upstream origin ${{ github.ref_name }}))
      shell: bash

        
          
