name: "Check python package"
description: "Check a python package and commit changes for quality"
inputs:
  use_version_check:
    required: false
    default: "false"
    description: "Whether to use the version check."
  version_check_path:
    required: false
    description: The path to file that contains the version string.
  version_check_variable:
    required: false
    description: The name of the version variable.
    default: __version__
runs:
  
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.repository.default_branch }}
    - uses: actions/checkout@v3
    - name: "Check version"
      run: |
        [ ${{ github.event.repository.default_branch }} == ${{ github.ref_name }} ] || $(cd ${{ github.action_path }} && python -m package_checker)
      shell: bash

        
          
