name: "Check python package"
description: "Check a python package and commit changes for quality"
inputs:
  version_path:
    required: false
    description: The path to file that contains the version string.
  version_variable:
    required: false
    description: The name of the version variable.
    default: __version__
runs:
  using: 'composite'
  steps:

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - uses: actions/checkout@v3
      with:
        path: ${{ github.event.repository.default_branch }}  
    - name: "test"
      shell: bash
      run: |
        cd ${{ github.workspace }} && echo $(ls -al)
    - name: "Check version"
      if: ${{ inputs.version_path }}
      
      run: |
        python ${{ github.action_path }}/scripts/check_version.py ${{ inputs.version_path }} ${{ inputs.version_variable }} ${{ github.event.repository.default_branch }}
      shell: bash
