name: "Check python package"
description: "Check a python package and commit changes for quality"
inputs:
  use_version_check:
    required: false
    default: "false"
    description: "Whether to use the version check."
  version_check_path:
    required: false
    description: The path to file that contains the version string.
    default: "-"
  version_check_variable:
    required: false
    description: The name of the version variable.
    default: __version__
runs:
  
  using: 'composite'
  steps:
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.repository.default_branch }}
    - uses: actions/checkout@v3
    - name: "Check version"
      run: |
        export PYTHONPATH=${{ github.action_path }}:$PYTHONPATH && pip install pyyaml && python -m package_checker --default-branch=${{ github.event.repository.default_branch }} --current-branch=${{ github.ref_name }} --use_version_check=${{ inputs.use_version_check }} --version_check_path=${{ inputs.version_check_path }} --version_check_variable=${{ inputs.version_check_variable }} --action-yaml=${{ github.action_path }}/action.yaml
      shell: bash
    - name: Commit changed files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git ls-files --others --exclude-standard | xargs git add
        git diff --name-only ${{ github.event.repository.default_branch }} ${{ github.ref_name }} --diff-filter=AMTR | xargs git add
        git diff --name-only ${{ github.event.repository.default_branch }} ${{ github.ref_name }} --diff-filter=D | xargs git rm
        git commit -m "Auto update files"
        git push --set-upstream origin ${{ github.ref_name }}

      shell: bash

        
          
