name: "Check python package"
description: "Check a python package and commit changes for quality"
inputs:
  version_path:
    required: false
    description: The path to file that contains the version string.
  version_variable:
    required: false
    description: The name of the version variable.
    default: __version__
runs:
  using: 'composite'
  steps:

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10' 
    - uses: actions/checkout@v3
      with:
        ref: ${{ github.event.repository.default_branch }}  
    - name: "Check version"
      if: ${{ inputs.version_path }}
      run: |
        python ${{ github.action_path }}/scripts/check_version.py ${{ inputs.version_path }} ${{ inputs.version_variable }} ${{ github.event.repository.default_branch }}
      shell: bash
    - name: "Update version"
      if: ${{ failure() }}
      shell: bash
      run: |
        git checkout ${{ github.ref_name }}
        python ${{ github.action_path }}/scripts/next_version.py ${{ inputs.version_path }} ${{ inputs.version_variable }} ${{ github.event.repository.default_branch }}  > ${{ inputs.version_path }}
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update micro version"
          git push
