name: Check python package
description: Check a python package and commit changes for quality
inputs:
  use_version_check:
    default: 'false'
    required: false
    description: Whether to run the version_check task.
  version_check_path:
    description: The path to the file containing the version string
    required: true
    default: '-'
  version_check_variable:
    description: The variable name in the path provided.
    required: true
    default: __version__
  use_black:
    default: 'false'
    required: false
    description: Whether to run the black task.
  black_args:
    description: The CLI args to be sent to black.
    required: true
    default: '-'
runs:
  using: composite
  steps:
  - uses: actions/setup-python@v4
    with:
      python-version: '3.10'
  - uses: actions/checkout@v3
    with:
      ref: ${{ github.event.repository.default_branch }}
  - uses: actions/checkout@v3
    with:
      ref: ${{ github.ref_name }}
  - name: Run package checker
    run: 'git checkout ${{ github.event.repository.default_branch }}

      git checkout ${{ github.ref_name }}

      export PYTHONPATH=${{ github.action_path }}:$PYTHONPATH && pip install ${{ github.action_path }} && python -m package_checker --default-branch=${{ github.event.repository.default_branch }} --current-branch=${{ github.ref_name }} --action-yaml=${{ github.action_path }}/action.yaml --use_version_check ${{ inputs.use_version_check }} --version_check_path ${{ inputs.version_check_path }} --version_check_variable ${{ inputs.version_check_variable }} --use_black ${{ inputs.use_black }} --black_args ${{ inputs.black_args }}'
    shell: bash
  - name: Commit changed files
    run: 'git status

      git config user.name github-actions;

      git config user.email github-actions@github.com;

      $(git add . && git commit -m "Auto update files" && git push --set-upstream origin ${{ github.ref_name }} ) || echo "Nothing to change"

      '
    shell: bash
